name: Java CI/CD with Maven

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests and generate reports
      run: |
        mvn test jacoco:report
        mvn pmd:pmd
        mvn checkstyle:checkstyle
        mvn spotbugs:spotbugs
    - name: List files in target directory for debugging
      run: |
        echo "Listing all files in the target directory:"
        ls -R target
    - name: Upload target directory as artifact
      uses: actions/upload-artifact@v3
      with:
        name: target-directory
        path: target
        if-no-files-found: error

  upload-reports-to-report-pages:
    needs: build-and-analyze
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: report-pages
    - name: Clean report-pages branch
      run: |
        git rm -rf .
        git clean -fxd
    - name: Download target directory artifact
      uses: actions/download-artifact@v3
      with:
        name: target-directory
        path: .
    - name: Remove unwanted directories and files
      run: |
        rm -rf classes maven-archiver maven-status/maven-compiler-plugin pmd/rulesets test-classes *.jar
    - name: List files for debugging
      run: |
        echo "Listing contents of the current directory:"
        ls -R
    - name: Add and commit reports to report-pages branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update reports" || echo "No changes to commit"
        git push --force origin report-pages
